### ISSUE TITLE
element-ui 의 el-dialog 과 함께 사용할 때 문제

### ISSUE THREAD

**Issue by min9nim** [wan2land/vue-daum-postcode#10]
element-ui 의 el-dialog  를 이용해 모달팝업으로 vue-duam-postcode 를 띄우면, 최초 한번은 잘 되는데 그 다음 다시 우편번호 찾기 팝업을 띄우면 우편번호 찾기 화면이 나타나지 않습니다.

우편번호찾기 화면이 나타나지 않을 때 해당 dom을 확인해 보면 아래와 같이 body에 아무 것도 없습니다. 
![image](https://user-images.githubusercontent.com/6068828/62588795-fc450b80-b901-11e9-9a14-c68742a62b46.png)

혹시 추가로 살펴봐야할 부분이 있다면 의견 주세요

enviroment)
nuxt + typescript + element-ui

**Comment by wan2land** [comment]
https://jsfiddle.net/wan2land/fw19qjy7/1/

대충 재현해봤는데 문제를 찾을 수 없었습니다. 문제가 발생되는 코드를 첨부해주실 수 있나요?
