### ISSUE TITLE
submitMode : false일때 ie11이슈 

### ISSUE THREAD

**Issue by zebra0303** [wan2land/vue-daum-postcode#107]
submitMode: false 를 추가했을때 ie11에서 주소검색시 '원하시는 페이지를 찾을 수가 없습니다.'란 오류가 나네요.
주소 검색어 쿼리를 encode를 안해서 발생하는 문제인듯 한데 혹시 해결 방법이 있을까요?

**Comment by wan2land** [comment]
답이 늦었습니다.

현재 라이브러리에서는 submitMode를 no-submit-mode라는 옵션으로 제공하고 있습니다. 에러가 발생하고 있는코드 + 환경(Vue인지 Nuxt인지) 첨부 부탁드립니다. 혹시, IE11을 대응하기 위해서 웹팩이나 바벨에 설정을 조금 수정하셨다면 이 또한 첨부 부탁드립니다.

"주소 검색어 쿼리를 encode를 안해서 발생하는 문제"라고 이야기하셨는데, 개발자 도구를 통해서 다른 모던브라우저(ex. Chrome)와 비교해보셨으리라 생각됩니다. IE에서 발생한 특이사항에 대해 관련한 스크린샷(개발자도구) 첨부해주시면 해당 문제를 재현하는데 도움이 됩니다.

혹시, Vue 컴포넌트를 제거하고, 그냥 바로 다음 우편번호 서비스를 직접 사용했을 때에도 동일한 에러가 발생한다면, https://github.com/daumPostcode/QnA/issues 여기에 문의하시는게 더 빠른 답변을 얻을 수 있습니다.

아래 코드는, vue-daum-postcode 없이 직접 다음 우편번호 서비스를 사용할 때 사용하는 코드입니다. (동작여부는 확인해보지 않았으나, 아마 동작할겁니다..)

```vue
<template>
  <div ref="container"></div>
</template>
<script>
export default {
  mounted() {
    new Promise((resolve, reject) => {
      (document.head || document.body).appendChild(Object.assign(document.createElement("script"), {
        src: 'https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js',
        async: true,
        charset: "utf8",
        onload() {
          resolve()
        },
        onerror() {
          reject(new Error(`Failed to load ${src}`))
        },
      }))
  	}).then(() => {
  	  new window.daum.Postcode({ /* 옵션 */ }).embed(this.$refs.container)
  	})
  }
}
</script>
```

**Comment by zebra0303** [comment]
바벨에서 vue를 사용하지 않고 바닐라로 구현을 했는데요 위 알려주신 QnA에 문의하도록 할께요. 답변 감사합니다.

**Comment by wan2land** [comment]
vue-daum-postcode 이슈로 확인된 경우 언제든지 다시 문의해주세요. :-)
