### ISSUE TITLE
ES5 지원 문제

### ISSUE THREAD

**Issue by chris-runn** [wan2land/vue-daum-postcode#11]
dist에 빌드된 결과물이 es5로 컴파일 되었나요?

**Comment by wan2land** [comment]
따로 타겟을 지정하지 않았기 때문에 babel env의 기본값인 es6로 컴파일 되었을겁니다.
es5로 실행하기 원하신다면, 직접 vue 파일을 사용하시면 됩니다.

```js
import VueDaumPostcode from 'vue-daum-postcode/src/vue-daum-postcode'

```

**Comment by chris-runn** [comment]
그렇게 해야겠군요. 답변 감사합니다 :)
