### ISSUE TITLE
크롬에서 무한로딩 현상이 일어나고 있습니다.

### ISSUE THREAD

**Issue by luiseok** [wan2land/vue-daum-postcode#2]
![output](https://user-images.githubusercontent.com/3125044/50434846-40127400-0922-11e9-9c8d-bf1c47e05602.gif)
보시다 시피 Demo사이트에서 조차 무한로딩이 일어나고 있습니다.
카카오 주소 검색사이트에서도 동일한 현상이 일어나는것 같습니다만, 어떻게 해결을 해야할지 마땅히 해결책이 떠오르지는 않습니다.
해결방법에 대해서 혹시 좋은 의견 있으신지 궁금합니다.

**Comment by wan2land** [comment]
확인중입니다! :-) 이슈 감사드려요.

**Comment by daumPostcode** [comment]
@luiseok 
안녕하세요~ 우편번호서비스 JS API 개발자입니다.
먼저 불편을 드려 죄송합니다.

해당 이슈의 경우 우편번호 서비스내 버그가 맞으며, 버그 자체가 좀 난해한 면이 있어서 수정에 시간이 걸릴 것 같습니다.

wan2land 님께서 저희쪽 issue페이지에 글 등록을 해주셨으며(https://github.com/daumPostcode/QnA/issues/399) 
현재 가능한 빠르게 처리를 할 수 있게 노력중이나, 완벽히 수정이 가능할지는 확답을 드리진 못할것 같습니다. (이전에 한번 실패했었거든요;;) 아무튼 불편하시겠지만 조금만 더 기다려 주시면 감사하겠습니다.

불편을 드려 죄송합니다.

**Comment by daumPostcode** [comment]
@luiseok @wan2land 
현재 해당 이슈 수정되어 배포되었습니다.
최신코어스크립트는 190107버전이며,
브라우저의 캐시를 한번 날린후에 테스트 부탁드립니다.

감사합니다.
