### ISSUE TITLE
컴포넌트의 onLoad 이벤트를 감지할 수 있을까요?

### ISSUE THREAD

**Issue by JunjaK** [wan2land/vue-daum-postcode#206]
초기에 daum-postcode를 불러오는데 시간이 1~2초 정도 걸리는 것 같습니다만,   
로딩 옵션이 따로 없어서 사용하는데 불편함이 있을 것 같습니다.  

로딩 옵션을 추가하거나,  
컴포넌트가 완전히 불러와졌을 때의 이벤트 같은 것이 있으면 좋을 것 같습니다.
혹시 추가할 생각이 있으신가요??

**Comment by wan2land** [comment]
loading 슬롯과, load 이벤트가 추가되었습니다. :-)

vue 2인 경우, `vue-daum-postcode@0.10.0` 를 이용하시고,
vue 3인 경우, `vue-daum-postcode@1.1.0` 를 이용하시면 됩니다.

예제: https://github.com/wan2land/vue-daum-postcode/blob/main/example/ExampleLoading.vue

**Comment by JunjaK** [comment]
빠른 수정 감사합니다!
