### ISSUE TITLE
초기에 styleHeight 지정가능하게 부탁드립니다.

### ISSUE THREAD

**Issue by kimjisung78** [wan2land/vue-daum-postcode#26]
저는 Vue에서 해당 컴포넌트를 아주 유용하게 잘 쓰고 있습니다. 
모달 창에서 주소 찾기를 연동했는데, 초기에 기본 styleHeight를 지정할 수 없어서 기본사이즈가 72px로 잡히게 됩니다. 그래서 다음 사진 같이 로딩됩니다.
<img width="673" alt="스크린샷 2019-12-26 오후 2 59 26" src="https://user-images.githubusercontent.com/15610432/71460743-85e17100-27f0-11ea-8272-d91b478f6f21.png">
prop으로 styleHeight를 px과 % 단위로 지정할 수 있을까요?

**Comment by wan2land** [comment]
`.vue-daum-postcode` 클래스를 이용하여 CSS 설정이 가능합니다.

```css
.vue-daum-postcode {
  height: 100px;
}
```

이 방식을 통해 해결되지 않았다면 문제 확인을 위해 간단한 소스코드도 첨부 부탁드립니다. :-)

**Comment by kimjisung78** [comment]
.vue-daum-postcode-container {
  width: 100% !important;
  height: 100% !important;
}
