### ISSUE TITLE
#26과 동일한 vue-daum-post-container height 72px 고정 이유

### ISSUE THREAD

**Issue by gurumzip** [wan2land/vue-daum-postcode#30]
#26 과 동일한 문제가 발생하구요.
처음 로드 시에는 정상적으로 주소 검색기가 나옵니다.
근데 주소 입력 마치고 다시 키면 vue-daum-postcode-container 클래스를 가진 태그가
72px로 고정되어버립니다. 초기화하면서 height 값을 가져고오는 코드가 왠지 있을듯한데 dialog로 뜨면서 초기화때 뭔가 값을 잘못가져와서 그렇게 되는것 같습니다.

왜 그런지 이유 알 수 있을까요??
아래와 같이 스타일줘서 강제로 444px에 맞추니 되긴하는데, 주소 검색시 결과가 많은 경우 
다이얼로그 창이 확대가 안되버려서 가능하면 72px로 안들어오고 첫 화면 띄울때처럼 정상적으로 뜨게끔 하고싶은데 무엇이 문제인지 잘 모르겠네요.ㅠ

.vue-daum-postcode-container {
  height: 444px !important;  
}

**Comment by wan2land** [comment]
`vue-daum-postcode-container`는 다음 우편번호 서비스가 바인딩 되어있는 dom 요소입니다.
우편번호 서비스 자체에서 검색 후, 검색 결과 전체 길이에 맞추어서 height가 조절됩니다.

다음 두가지 중 편한 방식으로 해결하는 걸 권장드립니다.

(1) Global로 CSS를 관리하시는 경우, `vue-daum-postcode-container`보다는 `vue-daum-postcode`를 사용해서 스타일을 적용하시면 됩니다.

```css
.vue-daum-postcode {
  max-height: 444px;
  overflow: scroll;
}
```

(2) scope로 css를 관리하시는 경우, `VueDaumPostcode`를 감싸는 container를 만들어서 스타일을 적용합니다.

```html
<style scoped>
.postcode {
  max-height: 444px;
  overflow: scroll;
}
</style>
<div class="postcode">
  <VueDaumPostcode />
</div>
```

위 두가지로도 해당 문제가 해결되지 않으시다면, 상황파악을 위해 소스코드 첨부 부탁드립니다!

**Comment by kismkof** [comment]
show/hide 이용하시는 분들 참고하셔도 좋습니다.

초기 로딩이 끝나면 div.vue-daum-postcode-container의 height가 72px 인데
주소창을 show 하는 시점에 div.vue-daum-postcode-container 의
style.height = null 하시면 그 이후부터는 높이가 자동으로 변경됩니다.

p.s complete 후에 주소창을 다시 show 하면 이전 검색 기록이 남아있는데
혹시 초기화 메서드나 속성을 아시는 분은 좀 알려주세요~

**Comment by wan2land** [comment]
@kismkof 

```
p.s complete 후에 주소창을 다시 show 하면 이전 검색 기록이 남아있는데
혹시 초기화 메서드나 속성을 아시는 분은 좀 알려주세요~
```

이 부분에 대해서 예시코드와 함께 별도 이슈 생성가능할까요? :-)
