### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by baramofme** [wan2land/vue-daum-postcode#4]
Cannot find type definition file for vue-daum-postcode. so, please make d.ts files.

Here's screenshot.

![image](https://user-images.githubusercontent.com/44565599/57822819-30f86980-77d0-11e9-8e3c-d04af9df26e8.png)

**Comment by wan2land** [comment]
뷰 컴포넌트에서 타입스크립트를 어떻게 지원하는지 찾아볼게요.

일단은 require를 통해서 사용하시면 타입스크립트 환경에서도 사용가능합니다. :-)

**Comment by ironyee** [comment]
`import VueDaumPostcode from "vue-daum-postcode";`
이렇게 해보실래요?

**Comment by wan2land** [comment]
처리완료.
