### ISSUE TITLE
scriptUrl option 이 작동안됩니다

### ISSUE THREAD

**Issue by say8425** [wan2land/vue-daum-postcode#54]
```js
// PROJECT/src/main.js
import VueDaumPostcode from 'vue-daum-postcode'

Vue.use(VueDaumPostcode, {
  scriptUrl: 'https://URL.URL/postcode.v2.js'
})
```

안녕하세요 새로 배포된 0.8.0 버전을 시도해봤는데, scriptUrl 이 작동이 안됩니다.

clone 떠봐서 한번 직접 추적해봤는데
최초 install 함수가 호출될 때는 당연히 options 가 잘 전달된 것을 확인했고,
**install.js:9** 의 `createVueDaumPostcode(remainOptions)` 가 실행되었을거라고 예상되는데,

이후 `vue-daum-postcode` component 가 렌더될 때,
mounted 시점에서 `options` parameter 가 텅 빈 object `{}` 로 찍히더라요.
아마 `options` parameter 가 전달이 안되서
기본 parameter 인, 텅 빈 object `{}` 가 된 거 같습니다.

이 이상은 잘 모르겠어서 어려운데, 혹시 한번 봐주실 수 있으시나요?

**Comment by wan2land** [comment]
Vue랑 Nuxt 둘다 테스트 환경 만들어서 동작시 이상없이 동작하였습니다.
해당 버그가 재현되는 최소한의 코드 작성이 가능할까요?

**Comment by say8425** [comment]
아!! 아니에요 제가 잘못했었어요.
main 에서 이미 import 하고 use 했으니까
그냥 바로 `vue-daum-postcode` component 쓰면 되는데,
제가 view 에서 vue-daum-postcode 를 또 import 하고 쓰고 있었네요 🤦‍♂️
그러니까 당연히 options 고 뭐고 main 에서 세팅한 건 홀라당 날라가버리죠 ㅋㅋㅋㅋ

바쁘신 와중에 소중한 시간을 쓰게해서 정말 죄송합니다.
코드는 훌륭하게 잘 작동하고 있습니다. 정말 고맙습니다ㅠ

이 이슈는 그냥 close 해주셔도 괜찮습니다 ✨
