### ISSUE TITLE
Unable to post message to file://. Recipient has origin null. 

### ISSUE THREAD

**Issue by sigpankyo** [wan2land/vue-daum-postcode#62]
안녕하세요. 갑자기 에러가 발생되서 문의 드립니다.
2월경에 만들었던 앱에서는 발생 되지 않았던 문제 인데요.
이번달 4월 신규앱을 만들던 과정에서 발생된 문제입니다.

폰갭으로 만들어 소스은 하나 인데요. 안드로이드은 정상 작동 합니다만,
아이폰에서 검색화면이 나오질 않고 
Unable to post message to file://. Recipient has origin null. 
에러가 발생됩니다.

해당 내용은 스크릿샷 으로 올렸습니다.
저 방법을 우회 할수 있는 방법이 있을까요?
![스크린샷 2020-04-21 오후 4 07 21](https://user-images.githubusercontent.com/1035154/79835798-474c7380-83ea-11ea-9b00-d2b98850b02e.png)

**Comment by wan2land** [comment]
일단은, 에러가 발생하는 소스코드가 daumcdn에 있네요. Vue Component에서 발생한 문제는 아닌 것 같아 보입니다. 여기 이슈보다는 폰갭관련 커뮤니티쪽에 문의하는게 더 좋아보입니다.

일단은, 폰갭을 해보지 않아 어떤상황인지 모르겠으나, 저의 얕은 지식으로 최대한 답변을 드려보자면,
file://index.html 이런 형식의 URL에서 해당 스크립트를 불러와서 벌어지는 문제로 보이네요. 불러온 외부 라이브러리 쪽에선 해결하긴 어렵다고 봅니다. (일반적으로 웹사이트에서 사용할 목적으로 만들어졌을 가능성이 높으니까요.)

postMessage를 접근하지 못하는 것으로 보아 CORS와 관련된 보안관련된 이슈일 가능성이 높아보입니다. 폰갭에서 관련한 설정을 찾아보시면 좋을 것 같아보입니다.

**Comment by sigpankyo** [comment]
> 일단은, 에러가 발생하는 소스코드가 daumcdn에 있네요. Vue Component에서 발생한 문제는 아닌 것 같아 보입니다. 여기 이슈보다는 폰갭관련 커뮤니티쪽에 문의하는게 더 좋아보입니다.
> 
> 일단은, 폰갭을 해보지 않아 어떤상황인지 모르겠으나, 저의 얕은 지식으로 최대한 답변을 드려보자면,
> file://index.html 이런 형식의 URL에서 해당 스크립트를 불러와서 벌어지는 문제로 보이네요. 불러온 외부 라이브러리 쪽에선 해결하긴 어렵다고 봅니다. (일반적으로 웹사이트에서 사용할 목적으로 만들어졌을 가능성이 높으니까요.)
> 
> postMessage를 접근하지 못하는 것으로 보아 CORS와 관련된 보안관련된 이슈일 가능성이 높아보입니다. 폰갭에서 관련한 설정을 찾아보시면 좋을 것 같아보입니다.

애플의 WKWebView 의 버그 같습니다. 2월경에 만들었던것 UIWebView 을 사용 하였습니다.
그리고 4월에 WKWebView 변경 했을때 해당 현상이 나옵니다.
혹시 몰라서 링크 걸어 드립니다.
https://github.com/apache/cordova-ios/issues/756
항상 건강 조심 하세요.
