### ISSUE TITLE
vue-daum-postcode - 검색어 초기화 기능

### ISSUE THREAD

**Issue by Ahngbeom** [wan2land/vue-daum-postcode#675]
vue-daum-postcode에서 검색어를 초기화시킬 수 있는 방법이 있을까요?

프로젝트에서 모달을 통해 vue-daum-postcode 컴포넌트를 띄우고 있는데, 모달이 닫히거나 주소 선택을 완료했을 때,
검색어를 초기화시켜주는 기능을 추가하고 싶습니다.

참고 문서에서는 onclose 이벤트가 존재하지 않는 것 같아 문의드립니다.
onclose 이벤트를 제어할 수 있다면 해결이 가능하지 않을까 싶습니다.

Vue3 & TypeScript 기반 프로젝트입니다.

**Comment by wan2land** [comment]
VueDaumPostcode는 임베딩 상태로 사용할 수 있게 만들어졌기 때문에 close이벤트가 불필요합니다.

모달이 닫힐 때 VueDaumPostcode 객체 자체를 같이 없애주시면 됩니다.

```
const isOpen = ref(false)

function onClose() {
  isOpen.value = false
}

<Modal @close="onClose">
  <VueDaumPostcode v-if="isOpen">
</Modal>
```

https://github.com/wan2land/vue-daum-postcode/blob/main/example/ExampleLoading.vue

**Comment by wan2land** [comment]
추가로 질문있으시면 계속 댓글 달아주시면 됩니다. :-)
