### ISSUE TITLE
Cannot read property 'postcode' of undefined

### ISSUE THREAD

**Issue by ChoWonmin** [wan2land/vue-daum-postcode#7]
안녕하세요.

index.js?3864:1 Uncaught (in promise) TypeError: Cannot read property 'postcode' of undefined

plugin을 사용하였을때 발생하는 에러 문구입니다.
혹시 이유를 아시나요??...

감사합니다.

**Comment by ChoWonmin** [comment]
아이고

네트워크 문제로 daum api를 불러오지 못 했었습니다.

감사합니다.

**Comment by wan2land** [comment]
이상없는거지요? :-) 문제있으면 또 이슈 달아주세요.
