### ISSUE TITLE
검색시 height가 늘어나는 것 컨트롤 여부

### ISSUE THREAD

**Issue by Karmantez** [wan2land/vue-daum-postcode#73]
## 개발환경
Vue: 2.6.11
Vuetify: 2.2.15

## 문제설명
 v-dialog에 vue-daum-postcode를 포함시켜 놓고 검색을 하게되면 일정시간 후에 검색결과가 나오면서 height가 늘어납니다. 이걸 컨트롤할 수 있는 방법이 있을까요?
그리고 공식 홈페이지의 문서에서 사용할 수 있는 event들을 모두 사용할 수 있나요?

**Comment by wan2land** [comment]
1. height를 어떻게 컨트롤 하고 싶은지 좀더 구체적으로 이야기 부탁드립니다. 무한정 height가 늘어나는걸 관리하고 싶은 상황이라면, 컴퍼넌트를 div로 감싼 후에, 그 div에 `max-height`를 적용하시면 됩니다.
2. 공식홈페이지 상에 있는 이벤트 중, `complete`만 사용가능합니다. `onresize`는 1번에서 설명드린대로, div로 감싸서 문제를 해결하는게 더 쉽다고 판단되어 구현하지 않았습니다. `onclose`는 팝업이라서 해당사항이 없습니다.  `onsearch`는 예전에 컴퍼넌트를 만들 때 못봤었는데, 추가되었나보군요. 추후 추가해두겠습니다. :)

**Comment by Karmantez** [comment]
답변 감사합니다.

**Comment by wan2land** [comment]
검색 후 새로운 페이지가 나타나면서 스크롤바가 맨 위로 이동하는 현상은 저도 발생하는 것 같습니다. 제 생각에는 정상적인 동작인 것 같습니다.

제가 이야기하는 동작과 @Karmantez 님께서 이야기하는 동작이 다를 수 있어, 버그로 느껴지는 동작을 동영상으로 캡쳐 후 첨부해주시면 이야기하기 좋을 것 같습니다.

**Comment by Karmantez** [comment]
답변 감사합니다.

가끔씩 이런 경우가 발생하는 듯 하는데 아마 프로젝트 상의 문제인듯 하여 반복적으로 발생되면 다시 이슈 발행하겠습니다.
