### ISSUE TITLE
VUE NUXT IE11 작동 안됩니다.

### ISSUE THREAD

**Issue by kjpar0317** [wan2land/vue-daum-postcode#8]
안녕하세요..
wan2land님이 만든 vue-daum-postcode를 사용하는데..
polyfill 적용한 상태에서 주소 모듈 추가시 스크립트 홀딩이 됩니다.
물론 주소 모듈을 빼면 잘 되고요..

따로 polyfill 추가해야하는지요? 현재 ES5, ES6, ES7, ES2017까지 한것같은데... 흠..

**Comment by wan2land** [comment]
현재 vue-daum-postcode는 npm main을 dist/index.js로 잡아놓았습니다. 빌드옵션에 IE 관련 내용은 추가할 예정이 없습니다.

다만, 직접 소스파일을 로드해서 사용하면 해당 문제가 해결될 것으로 추측됩니다.

기존에 `nuxt.config.js`에서 다음과 같이 설정했다면

```js
export default {
  ...
  modules: ['vue-daum-postcode/nuxt'],
  ...
}
```

이 부분은 삭제해주시고, Nuxt 플러그인 파일을 생성해서 다음과 같이 작성합니다.

```js
import Vue from "vue"
import VueDaumPostcode from "vue-daum-postcode/src" // 여기 경로가 바뀝니다.

Vue.use(VueDaumPostcode)
```

그리고 `nuxt.config.js`에 plugin 으로 설정하시기 바랍니다.

```js
export default {
  ...
  plugins: ['~/plugins/vue-daum-postcode']
  ...
}
```

**Comment by kjpar0317** [comment]
@wan2land 
npm으로 소스 받고 src에 vue-daum-post.js을 열어서 eslint 작업해주고 assets폴더에 넣고 plugin을 wan2land님 말대로 하니 잘 되네요.. 감사합니다~
답변도 감사드리고요 ^^

**Comment by wan2land** [comment]
`vue-daum-post.js` 이 파일은 복사해서 쓰는 것 보다 npm 경로 그대로 사용하는 편이 더 좋습니다. 추후에 패키지 업데이트라도 되면 다시 파일을 복사해서 써야하니까요.

복사하신 이유가 ESLint 때문이면, ESLint에서 node_modules 하위에 있는 내용을 처리안하도록 하면 됩니다.

https://eslint.org/docs/user-guide/configuring#ignoring-files-and-directories

**Comment by moonjoungyoung** [comment]
@wan2land 

저도 같은 이슈가 있습니다.

말씀하신대로 플러그인 파일을 생성하였고, 경로를 src 로 지정한 후 nano-loader install 이 필요하다고 하여 (직접 로드하므로 필요한 듯 합니다. 버전 고정해야 할 듯) install 후 실행했음에도 불구하고 구문 오류가 나네요.

```
/***/ "./node_modules/vue-daum-postcode/dist/index.js":
/*!******************************************************!*\
  !*** ./node_modules/vue-daum-postcode/dist/index.js ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {
```
마지막 줄에서 오류가 발생합니다.

**Comment by moonjoungyoung** [comment]
@wan2land 

@kjpar0317 님과 마찬가지로 파일을 따로 빼 해결하였습니다. 감사합니다.

nuxt.js 사용 중인데, 여기에서 사용하는 webpack 이 plugin 내에서 전역에 사용된 es6 문법을 변환해 주지 못하는 듯한 느낌이 듭니다. IE11 지원이 되지 않는다는 안내가 Readme 에 추가되면 좋을 것 같습니다.
