### ISSUE TITLE
데이터 바인딩 방법 볼 수 있는 codesandbox 있으면 도움이 되겠습니다

### ISSUE THREAD

**Issue by titusdecali** [wan2land/vue-daum-postcode#81]
Readme 에서 codesandbox 추가하시면 어떻게 data binding 해야하는지는 더 빨리 이해할 수 있을 것 같습니다.

아래와 같은 식으로 completed 을 썼는데...data가 안들어오네요.
![CleanShot 2020-06-22 at 14 03 41@2x](https://user-images.githubusercontent.com/4532534/85250341-417a1980-b491-11ea-95da-2d4f36edabf2.jpg)

![CleanShot 2020-06-22 at 14 05 04@2x](https://user-images.githubusercontent.com/4532534/85250395-64a4c900-b491-11ea-8bbe-47cb808715e7.jpg)

![CleanShot 2020-06-22 at 10 12 26@2x](https://user-images.githubusercontent.com/4532534/85239900-e6d0c580-b470-11ea-94a3-e84c4791dbbd.jpg)

이 package를 만들어 주셔서 감사합니다

**Comment by wan2land** [comment]
`README.md`에 [demo](https://wani.kr/vue-daum-postcode/)를 참고하시면 됩니다! :-)

```vue
<template>
  <vue-daum-postcode @complete="onComplete" />
</template>
<script>

export default {
  methods: {
    onComplete(data) {
      this.deliveryDetails.address.zonecode = data.zonecode
    },
  },
}
</script>
```
