### ISSUE TITLE
팝업은 어떻게 구현할 수 있나요?

### ISSUE THREAD

**Issue by taewo** [wan2land/vue-daum-postcode#9]
'우편번호찾기' 버튼을 클릭하면 Daum 우편번호 서비스 팝업이 띄어지게 
개발하고 싶은데 어떻게 하면 될까요?

VueDaumPostcode 컴포넌트를 모달에 담아야 하나요?

**Comment by wan2land** [comment]
컴포넌트로 작업한 소스라서, "다음우편번호"에서 지원해주는 팝업의 형태는 사용할 수 없습니다.

이야기하신대로 모달에 담아서 사용하시면 됩니다. :-)

**Comment by taewo** [comment]
@wan2land  넵 감사합니다 ^^
